---
title: "Pool 4 Lower Exploration"
author: "Amber Lee"
date: "6/3/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
```


```{r}
veg19 <- read.csv(file = "../2019 pool data/ltrm_vegsrs_data_lat_long.csv")
water19 <- read.csv(file = "../2019 pool data/ltrm_water_data_lat_long.csv")
```

## Vegetation data

```{r}
veg19 %>% 
  filter(POOL == "04",
         str_detect(MSTRATUM, "-L")) %>%
  select(DATE, DETRITUS, SBSTRATE, VEG_S, VEG_RF, 
         VEG_E, VEG_A, VEG_NRF, VEG_U,
         COV_NRF, COV_RF, COV_E,
         RAKE1, RAKE2, RAKE3, RAKE4, RAKE5, RAKE6) %>% head()

veg_4L <- veg19 %>% 
  filter(POOL == "04",
         str_detect(MSTRATUM, "-L")) %>%
  mutate(DATE = mdy(DATE))
```

Rake distribution

```{r}
veg_4L %>% 
  mutate(year = year(DATE)) %>%
  select(year, RAKE1, RAKE2, RAKE3, RAKE4, RAKE5, RAKE6) %>%
  pivot_longer(!year, names_to = "subsample_rake",
               values_to = "level") %>%
  group_by(year) %>%
  summarize(mean_level = mean(level),
            sd_level = sd(level)) %>%
  ggplot(aes(x = year, y = mean_level, 
             fill = sd_level)) +
  geom_point()
  
  # 
  # ggplot(aes(x = RAKE1)) +
  # geom_histogram()
```

Water depth

```{r}
veg_4L %>% 
  mutate(year = year(DATE)) %>%
  select(year, starts_with("DEPTH")) %>%
  pivot_longer(!year, names_to = "subsample",
               values_to = "depth") %>%
  ggplot(aes(x = year, y = depth, group = year)) +
  geom_boxplot()
  
  # 
  # ggplot(aes(x = RAKE1)) +
  # geom_histogram()
```

plant density

```{r}
veg_4L %>% 
  mutate(year = year(DATE)) %>%
  select(year, starts_with("DENSITY")) %>%
  pivot_longer(!year, names_to = "subsample",
               values_to = "density") %>%
  ggplot(aes(x = year, y = density, group = year)) +
  stat_summary(
    mapping = aes(x = year, y = density),
    fun.min = function(z) { quantile(z,0.25) },
    fun.max = function(z) { quantile(z,0.75) },
    fun = mean)
```

## Water data

```{r}

water19 %>%
  filter(FLDNUM == "1") %>%
  mutate(`Pool 4 Regions` = case_when(LONGITUDE <= -92.33 ~ "Lower",
                                      LONGITUDE >= -92.035 ~ "Upper",
                                      TRUE ~ "A lake")) %>%
  ggplot(aes(x = LATITUDE, y = LONGITUDE)) +
  geom_point(aes(color = `Pool 4 Regions`)) +
  geom_abline(intercept = -92.035, slope = 0) +
  geom_abline(intercept = -92.33, slope = 0) +
  ggtitle("Upper and Lower Pool 4")

```


```{r}

water_var <- c('TN','TP','TEMP','DO','TURB',
               'COND','VEL','SS','WDP','CHLcal','SECCHI')

water_4L %>% select(all_of(water_var), DATE) 

water_4L %>% mutate(year = year(DATE)) %>%
  ggplot(aes(y = SECCHI, group = year)) +
  geom_boxplot()

```


[website](umesc.usgs.gov/ltrm-home.html)


